version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: cat Dockerfile
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t joinez/docker-build:$TAG .
          docker login -u $HUB_USER -p $HUB_PASSWORD
          docker push joinez/docker-build:$TAG

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker_hub
